# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 819e6eef790eb039f08b287f8ceeacadcb10841a1472da8c9d8eab50b6a40afb8860174d5e9c6ec7c1fa4c5bd732176d91cf2c872f726efd09cc20d2b36ef853

test:
  secret_key_base: d82eb5ac3c1272eaf5938eb34d7e8dc564b0abe9874659d9f7f272104b070f58cb222f18370e6a314f23093db47fe2be2b35108bc24a5503570ff7507c9dd34f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
